@hostname = localhost
@port = 443
@sheme = https
@host = {{hostname}}:{{port}}
@base_url = {{sheme}}://{{hostname}}
@contentType = application/json
###
GET {{base_url}}/ HTTP/1.1
Accept: {{contentType}}
###
GET {{base_url}}/api/member/ HTTP/1.1
###
POST {{base_url}}/api/member/daftar HTTP/1.1
Content-Type: {{contentType}}

{
    "email" : "member@gmail.com",
    "name" : "member",
    "displayname" : "Member",
    "password" : "123",
    "repeatpassword" : "123"
}
###
@id = 6
###
GET {{base_url}}/api/member?id={{id}} HTTP/1.1
###
PATCH {{base_url}}/api/member/update/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
    "name" : "admin",
    "email" : "admin@gmail.com",
    "password" : "123",
    "repeatpassword" : "123",
    "displayname" : "admin",
    "type" : "writer"
}
###
DELETE {{base_url}}/api/member/delete/{{id}} HTTP/1.1
###
